image: node:16.3.0

stages:
  - deploy

variables:
  APP: "admin"

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  export GIT_BRANCH=''; 
      else 
      sed -i  's/LC-RUNCOMMAND/COPY nginx/nginx.beta.conf \/etc\/nginx\/nginx.conf/g' Dockerfile;
      export GIT_BRANCH=-$CI_COMMIT_REF_NAME ;  fi;
  script:
    - docker-compose  up -d --build
    - echo $GIT_BRANCH
    - cat Dockerfile
    - cat docker-compose.yaml
    - echo https://${APP}${GIT_BRANCH}.abclive.cloud  