image: node:16.3.0

stages:
  - deploy
  - notification

variables:
  APP: "admin"
  APPLOWERNAME: "admin"

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  export GIT_BRANCH='';
      export CICD_HOOK_URL="https://open.feishu.cn/open-apis/bot/v2/hook/180e3142-5b21-4442-ae35-f9dc96ee29c5";
      else
      export GIT_BRANCH=-$CI_COMMIT_REF_NAME ;
      export CICD_HOOK_URL="https://open.feishu.cn/open-apis/bot/v2/hook/f0b1358b-38ce-4f01-b629-64c0d2fbe854";
      fi;
    - sed -i  "s/LCAPP/${APP}${GIT_BRANCH}/g" ./deploy/docker-compose.yaml;
    - sed -i  "s/IMAGENAME/${APPLOWERNAME}${GIT_BRANCH}-${CI_COMMIT_SHORT_SHA}/g" ./deploy/docker-compose.yaml;
  script:
    - cat ./deploy/docker-compose.yaml
    - docker --version
    - docker-compose --version
    - docker-compose -f ./deploy/docker-compose.yaml  up -d --build
    - echo https://${APP}${GIT_BRANCH}.abclive.cloud

notification:
  stage: notification
  tags:
    - shell-1
  script:
    - . ./deploy/notification.sh
