image: node:16.3.0

variables:
  APP: "admin"

stages:
  - deploy
  - notification

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then
      export GIT_BRANCH='';
      sed -i  's/LC-RUNCOMMAND/pnpm run build/g' ./deploy/Dockerfile;
      else
      mv ./deploy/nginx/nginx.beta.conf ./deploy/nginx/nginx.conf;
      export GIT_BRANCH=-$CI_COMMIT_REF_NAME ;
      sed -i  's/LC-RUNCOMMAND/pnpm run beta/g' ./deploy/Dockerfile;
      fi;
    - sed -i  "s/lcApp/${APP}-${GIT_BRANCH}/g" ./deploy/docker-compose.yaml;
  script:
    - docker-compose -f ./deploy/docker-compose.yaml -p OauthFrontAdmin  up -d --build
    - echo https://${APP}${GIT_BRANCH}.abclive.cloud

notification:
  stage: notification
  tags:
    - shell-1
  script:
    - . ./deploy/notification.sh
