image: node:16.3.0

stages:
  - deploy
  - notification

variables:
  APP: "admin"

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  export GIT_BRANCH='';
      else
      mv ./deploy/nginx/nginx.beta.conf ./deploy/nginx/nginx.conf;
      export GIT_BRANCH=-$CI_COMMIT_REF_NAME ;  fi;
  script:
    - docker-compose  up -d --build
    - echo https://${APP}${GIT_BRANCH}.abclive.cloud

notification:
  stage: notification
  tags:
    - shell-1
  script:
    - . ./deploy/notification.sh
